### ISSUE TITLE
Authentication failure first boot

### ISSUE THREAD

**Issue by jossie67** [Piflyer/SmartDisplayPi#2]
Hi,

I like you cool project, 
On the first boot I get an error , 
Login : pi (automatic login)
Authentication failure.

Can you tell me what the password is, I tried "raspberry" that didn't work

Thanks

**Comment by Piflyer** [comment]
Hi there, I'm 99% sure I have set it to raspberry, if not, it would be 091521. It should automatically boot, but I will be rolling out an updated version in the coming weeks if I have time.

**Comment by jossie67** [comment]
Hi Tim,
Thanks
